# Generated by Django 4.2.14 on 2024-07-27 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("author", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("adventure", "Adventure"),
                            ("kids", "Children's Books"),
                            ("classics", "Classics"),
                            ("comics", "Comics and Graphic Novels"),
                            ("fantasy", "Fantasy"),
                            ("historical", "Historical Fiction"),
                            ("horror", "Horror"),
                            ("literary", "Literary Fiction"),
                            ("mystery", "Mystery"),
                            ("non_fiction", "Non-Fiction"),
                        ],
                        default="adventure",
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
