# Generated by Django 4.2.14 on 2024-07-27 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("lib_manage", "0004_remove_book_user_remove_usergetbooks_book_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="usergetbooks", name="book_id",),
        migrations.RemoveField(model_name="usergetbooks", name="user_id",),
        migrations.AddField(
            model_name="book",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="books",
                to="lib_manage.userreg",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="usergetbooks",
            name="book",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="lib_manage.book",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="usergetbooks",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="lib_manage.userreg",
            ),
            preserve_default=False,
        ),
    ]
