# Generated by Django 4.2.14 on 2024-07-27 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("lib_manage", "0005_remove_usergetbooks_book_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="book", name="user",),
        migrations.AlterField(
            model_name="usergetbooks",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_get_books",
                to="lib_manage.book",
            ),
        ),
        migrations.AlterField(
            model_name="usergetbooks",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_get_books",
                to="lib_manage.userreg",
            ),
        ),
    ]
