# Generated by Django 4.2.14 on 2024-07-28 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lib_manage", "0006_remove_book_user_alter_usergetbooks_book_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="book", name="qty", field=models.IntegerField(default=1),
        ),
    ]
