# Generated by Django 4.2.14 on 2024-07-30 15:32

from django.db import migrations, models
import lib_manage.models


class Migration(migrations.Migration):

    dependencies = [
        ("lib_manage", "0007_book_qty"),
    ]

    operations = [
        migrations.AddField(
            model_name="usergetbooks",
            name="dueDate",
            field=models.DateField(
                default=lib_manage.models.UserGetBooks.two_weeks_from_today
            ),
        ),
    ]
