# Generated by Django 4.2.14 on 2024-07-30 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lib_manage", "0009_userreg_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userreg", name="email", field=models.EmailField(max_length=255),
        ),
    ]
